# Generated by Django 3.2.16 on 2024-06-30 06:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepoGiris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_kodu', models.CharField(max_length=255)),
                ('urun_adi', models.CharField(max_length=255)),
                ('miktar', models.IntegerField()),
                ('tarih', models.DateTimeField()),
                ('depo_adi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DepoHareketleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_sirasi', models.CharField(max_length=255)),
                ('kullanici_kodu', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField()),
                ('hangi_depo', models.CharField(max_length=255)),
                ('stok_kodu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MusteriKayit',
            fields=[
                ('musteri_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('musteri_adi', models.CharField(max_length=255)),
                ('musteri_kodu', models.CharField(max_length=255)),
                ('adres', models.TextField()),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('musteri_adi', 'musteri_id', 'musteri_kodu')},
            },
        ),
        migrations.CreateModel(
            name='TeknolojikAlim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_kodu', models.CharField(max_length=255)),
                ('malzeme_tipi', models.CharField(max_length=255)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField()),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit')),
            ],
        ),
        migrations.CreateModel(
            name='Sac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_kodu', models.CharField(max_length=255)),
                ('proje', models.CharField(max_length=255)),
                ('kalinlik', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adet', models.IntegerField()),
                ('kalite', models.CharField(max_length=255)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField()),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_kodu', models.CharField(max_length=255)),
                ('proje', models.CharField(max_length=255)),
                ('kalinlik', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adet', models.IntegerField()),
                ('kalite', models.CharField(max_length=255)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField()),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit')),
            ],
        ),
        migrations.CreateModel(
            name='MotorReduktor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_kodu', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('guc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adet', models.IntegerField()),
                ('depo_secimi', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField()),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit')),
            ],
        ),
        migrations.CreateModel(
            name='Isleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_kodu', models.CharField(max_length=255)),
                ('islem_tipi', models.CharField(max_length=255)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField()),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit')),
            ],
        ),
        migrations.CreateModel(
            name='Boya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_kodu', models.CharField(max_length=255)),
                ('proje', models.CharField(max_length=255)),
                ('renk', models.CharField(max_length=255)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField()),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit')),
            ],
        ),
    ]
