# Generated by Django 3.2.16 on 2024-07-21 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusteriKayit',
            fields=[
                ('musteri_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('musteri_adi', models.CharField(max_length=255)),
                ('adres', models.TextField()),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('proje_kodu', models.CharField(max_length=255)),
                ('proje_genel', models.CharField(max_length=255)),
                ('proje_tarihi', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_musteri', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_musteri', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_kodu', models.CharField(max_length=255)),
                ('proje', models.CharField(max_length=255)),
                ('kalinlik', models.FloatField()),
                ('boy', models.FloatField()),
                ('en', models.FloatField()),
                ('adet', models.IntegerField()),
                ('kalite', models.CharField(max_length=255)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('olusturma_tarih', models.DateTimeField(auto_now=True)),
                ('son_edit_tarih', models.DateTimeField(null=True)),
                ('giris_aciklama', models.TextField(blank=True, null=True)),
                ('cikis_aciklama', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sac', to=settings.AUTH_USER_MODEL)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sac', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepoHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField(auto_now=True)),
                ('depo', models.CharField(max_length=255)),
                ('stok_kodu', models.CharField(max_length=255)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='musterikayit',
            constraint=models.UniqueConstraint(fields=('proje_kodu',), name='unique_proje_kodu'),
        ),
    ]
