# Generated by Django 3.2.16 on 2024-07-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sac',
            old_name='proje',
            new_name='proje_kodu',
        ),
        migrations.AlterField(
            model_name='sac',
            name='olusturma_tarih',
            field=models.DateTimeField(null=True),
        ),
    ]
