# Generated by Django 3.2.16 on 2024-07-28 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depohareket',
            name='proje',
        ),
        migrations.RemoveField(
            model_name='sac',
            name='proje',
        ),
        migrations.AddField(
            model_name='depohareket',
            name='proje_kodu',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sac',
            name='projekodu',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depohareket',
            name='musteri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='musterikayit',
            name='proje_kodu',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='boy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='en',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='kalinlik',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='musteri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sac',
            name='olusturma_tarih',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Yatak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri', models.CharField(max_length=255)),
                ('stok_kodu', models.CharField(max_length=255)),
                ('marka', models.CharField(max_length=255)),
                ('adet', models.IntegerField()),
                ('yatak_kodu', models.CharField(max_length=255)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('olusturma_tarih', models.DateTimeField(null=True)),
                ('son_edit_tarih', models.DateTimeField(null=True)),
                ('giris_aciklama', models.TextField(blank=True, null=True)),
                ('cikis_aciklama', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_yatak', to=settings.AUTH_USER_MODEL)),
                ('projekodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_yatak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeknolojikAlim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri', models.CharField(max_length=255)),
                ('stok_kodu', models.CharField(max_length=255)),
                ('malzeme_tipi', models.CharField(max_length=255)),
                ('malzeme_adi', models.CharField(max_length=255)),
                ('adet', models.IntegerField()),
                ('depo_secimi', models.CharField(max_length=255)),
                ('olusturma_tarih', models.DateTimeField(null=True)),
                ('son_edit_tarih', models.DateTimeField(null=True)),
                ('giris_aciklama', models.TextField(blank=True, null=True)),
                ('cikis_aciklama', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teknoloji', to=settings.AUTH_USER_MODEL)),
                ('projekodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teknoloji', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri', models.CharField(max_length=255)),
                ('stok_kodu', models.CharField(max_length=255)),
                ('kalinlik', models.FloatField(blank=True, null=True)),
                ('boy', models.FloatField(blank=True, null=True)),
                ('adet', models.IntegerField()),
                ('kalite', models.CharField(max_length=255)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('olusturma_tarih', models.DateTimeField(null=True)),
                ('son_edit_tarih', models.DateTimeField(null=True)),
                ('giris_aciklama', models.TextField(blank=True, null=True)),
                ('cikis_aciklama', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profil', to=settings.AUTH_USER_MODEL)),
                ('projekodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotorReduktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri', models.CharField(max_length=255)),
                ('stok_kodu', models.CharField(max_length=255)),
                ('marka', models.CharField(max_length=255)),
                ('kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devir', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adet', models.IntegerField()),
                ('depo_secimi', models.CharField(max_length=255)),
                ('olusturma_tarih', models.DateTimeField(null=True)),
                ('son_edit_tarih', models.DateTimeField(null=True)),
                ('giris_aciklama', models.TextField(blank=True, null=True)),
                ('cikis_aciklama', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_motor', to=settings.AUTH_USER_MODEL)),
                ('projekodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_motor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Isleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri', models.CharField(max_length=255)),
                ('stok_kodu', models.CharField(max_length=255)),
                ('cinsi', models.CharField(max_length=255)),
                ('yer', models.CharField(max_length=255)),
                ('adet', models.IntegerField()),
                ('depo_secimi', models.CharField(max_length=255)),
                ('olusturma_tarih', models.DateTimeField(null=True)),
                ('son_edit_tarih', models.DateTimeField(null=True)),
                ('giris_aciklama', models.TextField(blank=True, null=True)),
                ('cikis_aciklama', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_isleme', to=settings.AUTH_USER_MODEL)),
                ('projekodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_isleme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri', models.CharField(max_length=255)),
                ('stok_kodu', models.CharField(max_length=255)),
                ('renk', models.CharField(max_length=255)),
                ('marka', models.CharField(max_length=255)),
                ('cinsi', models.CharField(max_length=255)),
                ('adet', models.IntegerField()),
                ('kalite', models.CharField(max_length=255)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('olusturma_tarih', models.DateTimeField(null=True)),
                ('son_edit_tarih', models.DateTimeField(null=True)),
                ('giris_aciklama', models.TextField(blank=True, null=True)),
                ('cikis_aciklama', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boya', to=settings.AUTH_USER_MODEL)),
                ('projekodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_boya', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
