# Generated by Django 3.2.16 on 2024-07-23 23:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240723_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sac',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
