# Generated by Django 3.2.16 on 2024-07-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sac_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depohareket',
            name='proje',
        ),
        migrations.AddField(
            model_name='depohareket',
            name='proje_kodu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depohareket',
            name='musteri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='musterikayit',
            name='proje_kodu',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sac',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sac',
            name='musteri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sac',
            name='proje_kodu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu'),
        ),
    ]
