# Generated by Django 3.2.16 on 2024-07-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240725_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sac',
            old_name='proje_kodu',
            new_name='projekodu',
        ),
    ]
