# Generated by Django 3.2.16 on 2024-07-25 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_rename_proje_kodu_sac_projekodu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri', models.CharField(max_length=255)),
                ('stok_kodu', models.CharField(max_length=255)),
                ('renk', models.CharField(max_length=255)),
                ('marka', models.CharField(max_length=255)),
                ('cinsi', models.CharField(max_length=255)),
                ('adet', models.IntegerField()),
                ('kalite', models.CharField(max_length=255)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('olusturma_tarih', models.DateTimeField(null=True)),
                ('son_edit_tarih', models.DateTimeField(null=True)),
                ('giris_aciklama', models.TextField(blank=True, null=True)),
                ('cikis_aciklama', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boya', to=settings.AUTH_USER_MODEL)),
                ('projekodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_boya', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
