# Generated by Django 3.2.16 on 2024-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_motorreduktor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorreduktor',
            name='devir',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
