# Generated by Django 3.2.16 on 2024-07-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_alter_motorreduktor_devir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sac',
            name='en',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri', models.CharField(max_length=255)),
                ('stok_kodu', models.CharField(max_length=255)),
                ('kalinlik', models.FloatField()),
                ('boy', models.FloatField()),
                ('adet', models.IntegerField()),
                ('kalite', models.CharField(max_length=255)),
                ('depo_secimi', models.CharField(max_length=255)),
                ('olusturma_tarih', models.DateTimeField(null=True)),
                ('son_edit_tarih', models.DateTimeField(null=True)),
                ('giris_aciklama', models.TextField(blank=True, null=True)),
                ('cikis_aciklama', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profil', to=settings.AUTH_USER_MODEL)),
                ('projekodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
