# Generated by Django 3.2.16 on 2024-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20240728_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='boy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='kalinlik',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
