# Generated by Django 3.2.16 on 2024-07-28 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0012_auto_20240728_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok_kodu', models.CharField(max_length=255)),
                ('cinsi', models.CharField(max_length=255)),
                ('yer', models.CharField(max_length=255)),
                ('adet', models.IntegerField()),
                ('depo_secimi', models.CharField(max_length=255)),
                ('olusturma_tarih', models.DateTimeField(null=True)),
                ('son_edit_tarih', models.DateTimeField(null=True)),
                ('giris_aciklama', models.TextField(blank=True, null=True)),
                ('cikis_aciklama', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_isleme', to=settings.AUTH_USER_MODEL)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_isleme', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
