# Generated by Django 3.2.16 on 2024-07-28 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_isleme'),
    ]

    operations = [
        migrations.AddField(
            model_name='isleme',
            name='projekodu',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='home.musterikayit', to_field='proje_kodu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='isleme',
            name='musteri',
            field=models.CharField(max_length=255),
        ),
    ]
